SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Create the fn in the specified schema
CREATE FUNCTION [dbo].[MTO_CATEGORIAS] (
    @LISTAGSR VARCHAR(50),
    @NIVELES int,
    @FECHADEMODIFICACION DATETIME
)
RETURNS @mtoCategorias TABLE (
    ID_CATEGORIA nvarchar(10)
    ,ID_PADRE nvarchar(10)
    ,POSICION int
    ,NOMBRE nvarchar(150)
    ,ACTIVO int
    ,FECHAMODIFICACION DATETIME
    --,META_TITLE nvarchar(150)
    --,META_KEYWORDS nvarchar(150)
    --,META_DESCRIPTION nvarchar(150)
)
AS
BEGIN
    INSERT @mtoCategorias
    SELECT r.CODIGO AS ID_CATEGORIA
        ,'' AS ID_PADRE
        ,0 AS POSICION
        ,SUBSTRING(r.DESCRIPCION,1,150) AS NOMBRE
        ,1 AS ACTIVO
        ,@FECHADEMODIFICACION AS FECHAMODIFICACION
    FROM FACT0010 r
    UNION ALL 
    SELECT sr.CODIGO AS ID_CATEGORIA
        ,STR(sr.COD_RUBRO) AS ID_PADRE
        ,1 AS POSICION
        ,SUBSTRING(sr.DESCRIPCION,1,150) AS NOMBRE
        ,1 AS ACTIVO
        ,@FECHADEMODIFICACION AS FECHAMODIFICACION
    FROM FACT0048 sr
    INNER JOIN FACT0010 r ON (r.CODIGO = sr.COD_RUBRO)
    ORDER BY POSICION, NOMBRE
    RETURN
END;
GO
