SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[MTO_MARCAS] (
    CODIGOMARCA,
    NOMBRE,
    --FECHACREACION,
    --FECHAMODIFICACION,
    --ACTIVO,
    --META_TITLE,
    --META_KEYWORDS,
    --META_DESCRIPTION,
    DESCRIPCION_CORTA,
    DESCRIPCION_LARGA
)
AS
  SELECT IDMARCA
    ,DESCRIPCION
    ,DESCRIPCION
    ,DESCRIPCION
  FROM FACT2056
GO
